export namespace ROUTES_TYPES {
  export type MAIN_DRAWER = 'MAIN_DRAWER';
  // stack
  export type MAIN_STACK = 'MAIN_STACK';
  export type MODAL_STACK = 'MODAL_STACK';
  export type AUTHORIZED_STACK = 'AUTHORIZED_STACK';
  export type UNAUTHORIZED_STACK = 'UNAUTHORIZED_STACK';
  export type HOME_STACK = 'HOME_STACK';
  export type PROFILE_STACK = 'PROFILE_STACK';
  // HOME
  export type HOME_SCREEN = 'HOME_SCREEN';
  export type NOTIFICATION = 'NOTIFICATION';
  export type TEXT_DATA_UPDATE_SCREEN = 'TEXT_DATA_UPDATE_SCREEN';
  export type BASE = 'BASE';
  export type PROFILE_SCREEN = 'PROFILE_SCREEN';
  export type PERSONAL_INFO_SCREEN = 'PERSONAL_INFO_SCREEN';
  export type LOGIN_SCREEN = 'LOGIN_SCREEN';
  export type REGISTER = 'REGISTER';
  export type PROMO = 'PROMO';
  export type SPLASH_SCREEN = 'SPLASH_SCREEN';
  export type ONBOARDING_SCREEN = 'ONBOARDING_SCREEN';
  export type SETTING_SCREEN = 'SETTING_SCREEN';
  export type FEEDBACK_SCREEN = 'FEEDBACK_SCREEN';
}

export interface ROUTES_TYPE {
  MAIN_DRAWER: 'MAIN_DRAWER';
  // stack
  MAIN_STACK: 'MAIN_STACK';
  MODAL_STACK: 'MODAL_STACK';
  AUTHORIZED_STACK: 'AUTHORIZED_STACK';
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK';
  HOME_STACK: 'HOME_STACK';
  PROFILE_STACK: 'PROFILE_STACK';
  NOTIFICATION_STACK: 'NOTIFICATION_STACK';
  // HOME
  HOME_SCREEN: 'HOME_SCREEN';
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN';
  TEXT_DATA_UPDATE_SCREEN: ROUTES_TYPES.TEXT_DATA_UPDATE_SCREEN;
  BASE: 'BASE';
  PROFILE_SCREEN: 'PROFILE_SCREEN';
  PERSONAL_INFO_SCREEN: 'PERSONAL_INFO_SCREEN';
  LOGIN_SCREEN: 'LOGIN_SCREEN';
  REGISTER: 'REGISTER';
  PROMO: 'PROMO';
  SPLASH_SCREEN: 'SPLASH_SCREEN';
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN';
  SETTING_SCREEN: 'SETTING_SCREEN';
  FEEDBACK_SCREEN: 'FEEDBACK_SCREEN';
}

const ROUTES: ROUTES_TYPE = {
  //drawer
  MAIN_DRAWER: 'MAIN_DRAWER',
  // stack
  MAIN_STACK: 'MAIN_STACK',
  MODAL_STACK: 'MODAL_STACK',
  AUTHORIZED_STACK: 'AUTHORIZED_STACK',
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK',
  HOME_STACK: 'HOME_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  NOTIFICATION_STACK: 'NOTIFICATION_STACK',
  // HOME
  HOME_SCREEN: 'HOME_SCREEN',
  NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
  TEXT_DATA_UPDATE_SCREEN: 'TEXT_DATA_UPDATE_SCREEN',
  BASE: 'BASE',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PERSONAL_INFO_SCREEN: 'PERSONAL_INFO_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER: 'REGISTER',
  PROMO: 'PROMO',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  FEEDBACK_SCREEN: 'FEEDBACK_SCREEN',
};

export const ROUTE_TABS = {
  MAIN_TAB: 'MAIN_TAB',
};

export default ROUTES;
