export namespace ROUTES_TYPES {
  export type HOME = 'HOME';
}

const ROUTES = {
  // stack
  MAIN_STACK: 'MAIN_STACK',
  MODAL_STACK: 'MODAL_STACK',
  AUTHORIZED_STACK: 'AUTHORIZED_STACK',
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK',
  // HOME
  HOME: 'HOME',
  NOTIFICATION: 'NOTIFICATION',
  BASE: 'BASE',
  PROFILE: 'PROFILE',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER: 'REGISTER',
  PROMO: 'PROMO',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
};

export const ROUTE_TABS = {
  MAIN_TAB: 'MAIN_TAB',
};

export default ROUTES;
