export namespace ROUTES_TYPES {
  export type HOME = 'HOME';
}

const ROUTES = {
  //drawer
  MAIN_DRAWER: 'MAIN_DRAWER',
  // stack
  MAIN_STACK: 'MAIN_STACK',
  MODAL_STACK: 'MODAL_STACK',
  AUTHORIZED_STACK: 'AUTHORIZED_STACK',
  UNAUTHORIZED_STACK: 'UNAUTHORIZED_STACK',
  HOME_STACK: 'HOME_STACK',
  PROFILE_STACK: 'PROFILE_STACK',
  // HOME
  HOME_SCREEN: 'HOME_SCREEN',
  NOTIFICATION: 'NOTIFICATION',
  BASE: 'BASE',
  PROFILE_SCREEN: 'PROFILE_SCREEN',
  PERSONAL_INFO_SCREEN: 'PERSONAL_INFO_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER: 'REGISTER',
  PROMO: 'PROMO',
  SPLASH_SCREEN: 'SPLASH_SCREEN',
  ONBOARDING_SCREEN: 'ONBOARDING_SCREEN',
  SETTING_SCREEN: 'SETTING_SCREEN',
  FEEDBACK_SCREEN: 'FEEDBACK_SCREEN',
};

export const ROUTE_TABS = {
  MAIN_TAB: 'MAIN_TAB',
};

export default ROUTES;
